<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geobuf.proto

namespace MBolli\PhpGeobuf\Data\Geometry;

use UnexpectedValueException;

/**
 * Protobuf type <code>MBolli.PhpGeobuf.Data.Geometry.Type</code>
 */
class Type {
    /**
     * Generated from protobuf enum <code>POINT = 0;</code>
     */
    public const POINT = 0;
    /**
     * Generated from protobuf enum <code>MULTIPOINT = 1;</code>
     */
    public const MULTIPOINT = 1;
    /**
     * Generated from protobuf enum <code>LINESTRING = 2;</code>
     */
    public const LINESTRING = 2;
    /**
     * Generated from protobuf enum <code>MULTILINESTRING = 3;</code>
     */
    public const MULTILINESTRING = 3;
    /**
     * Generated from protobuf enum <code>POLYGON = 4;</code>
     */
    public const POLYGON = 4;
    /**
     * Generated from protobuf enum <code>MULTIPOLYGON = 5;</code>
     */
    public const MULTIPOLYGON = 5;
    /**
     * Generated from protobuf enum <code>GEOMETRYCOLLECTION = 6;</code>
     */
    public const GEOMETRYCOLLECTION = 6;

    private static $valueToName = [
        self::POINT => 'POINT',
        self::MULTIPOINT => 'MULTIPOINT',
        self::LINESTRING => 'LINESTRING',
        self::MULTILINESTRING => 'MULTILINESTRING',
        self::POLYGON => 'POLYGON',
        self::MULTIPOLYGON => 'MULTIPOLYGON',
        self::GEOMETRYCOLLECTION => 'GEOMETRYCOLLECTION',
    ];

    public static function name($value) {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                __CLASS__,
                $value
            ));
        }
        return self::$valueToName[$value];
    }


    public static function value($name) {
        $const = __CLASS__ . '::' . mb_strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                __CLASS__,
                $name
            ));
        }
        return constant($const);
    }
}
