<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geobuf.proto

namespace MBolli\PhpGeobuf\Geometry;

use UnexpectedValueException;

/**
 * Protobuf type <code>Data.Geometry.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>POINT = 0;</code>
     */
    const POINT = 0;
    /**
     * Generated from protobuf enum <code>MULTIPOINT = 1;</code>
     */
    const MULTIPOINT = 1;
    /**
     * Generated from protobuf enum <code>LINESTRING = 2;</code>
     */
    const LINESTRING = 2;
    /**
     * Generated from protobuf enum <code>MULTILINESTRING = 3;</code>
     */
    const MULTILINESTRING = 3;
    /**
     * Generated from protobuf enum <code>POLYGON = 4;</code>
     */
    const POLYGON = 4;
    /**
     * Generated from protobuf enum <code>MULTIPOLYGON = 5;</code>
     */
    const MULTIPOLYGON = 5;
    /**
     * Generated from protobuf enum <code>GEOMETRYCOLLECTION = 6;</code>
     */
    const GEOMETRYCOLLECTION = 6;

    private static array $valueToName = [
        self::POINT => 'POINT',
        self::MULTIPOINT => 'MULTIPOINT',
        self::LINESTRING => 'LINESTRING',
        self::MULTILINESTRING => 'MULTILINESTRING',
        self::POLYGON => 'POLYGON',
        self::MULTIPOLYGON => 'MULTIPOLYGON',
        self::GEOMETRYCOLLECTION => 'GEOMETRYCOLLECTION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}
