<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geobuf.proto

namespace MBolli\PhpGeobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Geobuf;

/**
 * Generated from protobuf message <code>Data.Feature</code>
 */
class Feature extends Message
{
    /**
     * Generated from protobuf field <code>.Data.Geometry geometry = 1;</code>
     */
    protected ?Geometry $geometry = null;
    /**
     * unique values
     *
     * Generated from protobuf field <code>repeated .Data.Value values = 13;</code>
     */
    private array $values;
    /**
     * pairs of key/value indexes
     *
     * Generated from protobuf field <code>repeated uint32 properties = 14 [packed = true];</code>
     */
    private array $properties;
    /**
     * arbitrary properties
     *
     * Generated from protobuf field <code>repeated uint32 custom_properties = 15 [packed = true];</code>
     */
    private array $custom_properties;
    protected $id_type;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type Geometry $geometry
     *     @type string $id
     *     @type int|string $int_id
     *     @type Value[]|RepeatedField $values
     *           unique values
     *     @type int[]|RepeatedField $properties
     *           pairs of key/value indexes
     *     @type int[]|RepeatedField $custom_properties
     *           arbitrary properties
     * }
     */
    public function __construct($data = NULL) {
        Geobuf::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Data.Geometry geometry = 1;</code>
     * @return Geometry|null
     */
    public function getGeometry(): ?Geometry
    {
        return $this->geometry;
    }

    public function hasGeometry(): bool
    {
        return isset($this->geometry);
    }

    public function clearGeometry(): void
    {
        unset($this->geometry);
    }

    /**
     * Generated from protobuf field <code>.Data.Geometry geometry = 1;</code>
     * @param Geometry $var
     * @return Feature
     * @throws \Exception
     */
    public function setGeometry(Geometry $var): Feature
    {
        GPBUtil::checkMessage($var, Geometry::class);
        $this->geometry = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string id = 11;</code>
     * @return string
     */
    public function getId(): string
    {
        return $this->readOneof(11);
    }

    public function hasId(): bool
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>string id = 11;</code>
     * @param string $var
     * @return Feature
     */
    public function setId(string $var): Feature
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint64 int_id = 12;</code>
     * @return int
     */
    public function getIntId(): int
    {
        return $this->readOneof(12);
    }

    public function hasIntId(): bool
    {
        return $this->hasOneof(12);
    }

    /**
     * Generated from protobuf field <code>sint64 int_id = 12;</code>
     * @param int $var
     * @return Feature
     */
    public function setIntId(int $var): Feature
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * unique values
     *
     * Generated from protobuf field <code>repeated .Data.Value values = 13;</code>
     * @return Value[]|RepeatedField
     */
    public function getValues(): array
    {
        return $this->values;
    }

    /**
     * unique values
     *
     * Generated from protobuf field <code>repeated .Data.Value values = 13;</code>
     * @param Value[]|RepeatedField $var
     * @return Feature
     */
    public function setValues($var): Feature
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Value::class);
        $this->values = $arr;

        return $this;
    }

    /**
     * pairs of key/value indexes
     *
     * Generated from protobuf field <code>repeated uint32 properties = 14 [packed = true];</code>
     * @return int[]|RepeatedField
     */
    public function getProperties(): RepeatedField
    {
        return $this->properties;
    }

    /**
     * pairs of key/value indexes
     *
     * Generated from protobuf field <code>repeated uint32 properties = 14 [packed = true];</code>
     * @param int[]|RepeatedField $var
     * @return Feature
     */
    public function setProperties($var): Feature
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->properties = $arr;

        return $this;
    }

    /**
     * arbitrary properties
     *
     * Generated from protobuf field <code>repeated uint32 custom_properties = 15 [packed = true];</code>
     * @return int[]|RepeatedField
     */
    public function getCustomProperties(): RepeatedField
    {
        return $this->custom_properties;
    }

    /**
     * arbitrary properties
     *
     * Generated from protobuf field <code>repeated uint32 custom_properties = 15 [packed = true];</code>
     * @param int[]|RepeatedField $var
     * @return Feature
     */
    public function setCustomProperties($var): Feature
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->custom_properties = $arr;

        return $this;
    }

    /**
     * @return string
     */
    public function getIdType(): string
    {
        return $this->whichOneof("id_type");
    }

}
