<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geobuf.proto

namespace MBolli\PhpGeobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Geobuf;

/**
 * Generated from protobuf message <code>Data.FeatureCollection</code>
 */
class FeatureCollection extends Message
{
    /**
     * Generated from protobuf field <code>repeated .Data.Feature features = 1;</code>
     */
    private array $features;
    /**
     * Generated from protobuf field <code>repeated .Data.Value values = 13;</code>
     */
    private array $values;
    /**
     * Generated from protobuf field <code>repeated uint32 custom_properties = 15 [packed = true];</code>
     */
    private array $custom_properties;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type Feature[]|RepeatedField $features
     *     @type Value[]|RepeatedField $values
     *     @type int[]|RepeatedField $custom_properties
     * }
     */
    public function __construct($data = NULL) {
        Geobuf::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Data.Feature features = 1;</code>
     * @return Feature[]|RepeatedField
     */
    public function getFeatures(): array
    {
        return $this->features;
    }

    /**
     * Generated from protobuf field <code>repeated .Data.Feature features = 1;</code>
     * @param Feature[]|RepeatedField $var
     * @return FeatureCollection
     */
    public function setFeatures($var): FeatureCollection
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Feature::class);
        $this->features = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Data.Value values = 13;</code>
     * @return Value[]|RepeatedField
     */
    public function getValues(): array
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>repeated .Data.Value values = 13;</code>
     * @param Value[]|RepeatedField $var
     * @return FeatureCollection
     */
    public function setValues(array $var): FeatureCollection
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Value::class);
        $this->values = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 custom_properties = 15 [packed = true];</code>
     * @return int[]|RepeatedField
     */
    public function getCustomProperties(): array
    {
        return $this->custom_properties;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 custom_properties = 15 [packed = true];</code>
     * @param int[]|RepeatedField $var
     * @return FeatureCollection
     */
    public function setCustomProperties($var): FeatureCollection
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->custom_properties = $arr;

        return $this;
    }

}
