<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geobuf.proto

namespace MBolli\PhpGeobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Geobuf;
use MBolli\PhpGeobuf\Geometry\Type;

/**
 * Generated from protobuf message <code>Data.Geometry</code>
 */
class Geometry extends Message
{
    /**
     * Generated from protobuf field <code>.Data.Geometry.Type type = 1;</code>
     */
    protected ?int $type = null;
    /**
     * coordinate structure in lengths
     *
     * Generated from protobuf field <code>repeated uint32 lengths = 2 [packed = true];</code>
     */
    private $lengths;
    /**
     * delta-encoded integer values
     *
     * Generated from protobuf field <code>repeated sint64 coords = 3 [packed = true];</code>
     */
    private $coords;
    /**
     * Generated from protobuf field <code>repeated .Data.Geometry geometries = 4;</code>
     */
    private $geometries;
    /**
     * Generated from protobuf field <code>repeated .Data.Value values = 13;</code>
     */
    private $values;
    /**
     * Generated from protobuf field <code>repeated uint32 custom_properties = 15 [packed = true];</code>
     */
    private $custom_properties;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type int[]|RepeatedField $lengths
     *           coordinate structure in lengths
     *     @type int[]|string[]|RepeatedField $coords
     *           delta-encoded integer values
     *     @type Geometry[]|RepeatedField $geometries
     *     @type Value[]|RepeatedField $values
     *     @type int[]|RepeatedField $custom_properties
     * }
     */
    public function __construct($data = NULL) {
        Geobuf::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Data.Geometry.Type type = 1;</code>
     * @return int
     */
    public function getType(): ?int
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.Data.Geometry.Type type = 1;</code>
     * @param int $var
     * @return Geometry
     */
    public function setType($var): Geometry
    {
        GPBUtil::checkEnum($var, Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * coordinate structure in lengths
     *
     * Generated from protobuf field <code>repeated uint32 lengths = 2 [packed = true];</code>
     * @return RepeatedField
     */
    public function getLengths()
    {
        return $this->lengths;
    }

    /**
     * coordinate structure in lengths
     *
     * Generated from protobuf field <code>repeated uint32 lengths = 2 [packed = true];</code>
     * @param int[]|RepeatedField $var
     * @return Geometry
     */
    public function setLengths($var): Geometry
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->lengths = $arr;

        return $this;
    }

    /**
     * delta-encoded integer values
     *
     * Generated from protobuf field <code>repeated sint64 coords = 3 [packed = true];</code>
     * @return RepeatedField
     */
    public function getCoords()
    {
        return $this->coords;
    }

    /**
     * delta-encoded integer values
     *
     * Generated from protobuf field <code>repeated sint64 coords = 3 [packed = true];</code>
     * @param int[]|string[]|RepeatedField $var
     * @return Geometry
     */
    public function setCoords($var): Geometry
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::SINT64);
        $this->coords = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Data.Geometry geometries = 4;</code>
     * @return RepeatedField
     */
    public function getGeometries()
    {
        return $this->geometries;
    }

    /**
     * Generated from protobuf field <code>repeated .Data.Geometry geometries = 4;</code>
     * @param Geometry[]|RepeatedField $var
     * @return $this
     */
    public function setGeometries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Geometry::class);
        $this->geometries = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Data.Value values = 13;</code>
     * @return RepeatedField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>repeated .Data.Value values = 13;</code>
     * @param Value[]|RepeatedField $var
     * @return Geometry
     */
    public function setValues($var): Geometry
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Value::class);
        $this->values = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 custom_properties = 15 [packed = true];</code>
     * @return RepeatedField
     */
    public function getCustomProperties()
    {
        return $this->custom_properties;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 custom_properties = 15 [packed = true];</code>
     * @param int[]|RepeatedField $var
     * @return Geometry
     */
    public function setCustomProperties($var): Geometry
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT32);
        $this->custom_properties = $arr;

        return $this;
    }

}
