<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geobuf.proto

namespace MBolli\PhpGeobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Geobuf;

/**
 * Generated from protobuf message <code>Data.Value</code>
 */
class Value extends Message
{
    protected $value_type;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $string_value
     *     @type float $double_value
     *     @type int|string $pos_int_value
     *     @type int|string $neg_int_value
     *     @type bool $bool_value
     *     @type string $json_value
     * }
     */
    public function __construct($data = NULL) {
        Geobuf::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string string_value = 1;</code>
     * @return string
     */
    public function getStringValue()
    {
        return $this->readOneof(1);
    }

    public function hasStringValue()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>string string_value = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStringValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>double double_value = 2;</code>
     * @return float
     */
    public function getDoubleValue()
    {
        return $this->readOneof(2);
    }

    public function hasDoubleValue()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>double double_value = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setDoubleValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 pos_int_value = 3;</code>
     * @return int|string
     */
    public function getPosIntValue()
    {
        return $this->readOneof(3);
    }

    public function hasPosIntValue()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>uint64 pos_int_value = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPosIntValue($var)
    {
        GPBUtil::checkUint64($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 neg_int_value = 4;</code>
     * @return int|string
     */
    public function getNegIntValue()
    {
        return $this->readOneof(4);
    }

    public function hasNegIntValue()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>uint64 neg_int_value = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNegIntValue($var)
    {
        GPBUtil::checkUint64($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool bool_value = 5;</code>
     * @return bool
     */
    public function getBoolValue()
    {
        return $this->readOneof(5);
    }

    public function hasBoolValue()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>bool bool_value = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolValue($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string json_value = 6;</code>
     * @return string
     */
    public function getJsonValue()
    {
        return $this->readOneof(6);
    }

    public function hasJsonValue()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>string json_value = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setJsonValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValueType()
    {
        return $this->whichOneof("value_type");
    }

}
