<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geobuf.proto

namespace MBolli\PhpGeobuf\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MBolli.PhpGeobuf.Data.Geometry</code>
 */
class Geometry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.MBolli.PhpGeobuf.Data.Geometry.Type type = 1;</code>
     */
    protected $type = 0;
    /**
     * coordinate structure in lengths
     *
     * Generated from protobuf field <code>repeated uint32 lengths = 2 [packed = true];</code>
     */
    private $lengths;
    /**
     * delta-encoded integer values
     *
     * Generated from protobuf field <code>repeated sint64 coords = 3 [packed = true];</code>
     */
    private $coords;
    /**
     * Generated from protobuf field <code>repeated .MBolli.PhpGeobuf.Data.Geometry geometries = 4;</code>
     */
    private $geometries;
    /**
     * Generated from protobuf field <code>repeated .MBolli.PhpGeobuf.Data.Value values = 13;</code>
     */
    private $values;
    /**
     * Generated from protobuf field <code>repeated uint32 custom_properties = 15 [packed = true];</code>
     */
    private $custom_properties;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $lengths
     *           coordinate structure in lengths
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $coords
     *           delta-encoded integer values
     *     @type \MBolli\PhpGeobuf\Data\Geometry[]|\Google\Protobuf\Internal\RepeatedField $geometries
     *     @type \MBolli\PhpGeobuf\Data\Value[]|\Google\Protobuf\Internal\RepeatedField $values
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $custom_properties
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Geobuf::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.MBolli.PhpGeobuf.Data.Geometry.Type type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.MBolli.PhpGeobuf.Data.Geometry.Type type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \MBolli\PhpGeobuf\Data\Geometry\Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * coordinate structure in lengths
     *
     * Generated from protobuf field <code>repeated uint32 lengths = 2 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLengths()
    {
        return $this->lengths;
    }

    /**
     * coordinate structure in lengths
     *
     * Generated from protobuf field <code>repeated uint32 lengths = 2 [packed = true];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLengths($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->lengths = $arr;

        return $this;
    }

    /**
     * delta-encoded integer values
     *
     * Generated from protobuf field <code>repeated sint64 coords = 3 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCoords()
    {
        return $this->coords;
    }

    /**
     * delta-encoded integer values
     *
     * Generated from protobuf field <code>repeated sint64 coords = 3 [packed = true];</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCoords($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::SINT64);
        $this->coords = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MBolli.PhpGeobuf.Data.Geometry geometries = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGeometries()
    {
        return $this->geometries;
    }

    /**
     * Generated from protobuf field <code>repeated .MBolli.PhpGeobuf.Data.Geometry geometries = 4;</code>
     * @param \MBolli\PhpGeobuf\Data\Geometry[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGeometries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \MBolli\PhpGeobuf\Data\Geometry::class);
        $this->geometries = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MBolli.PhpGeobuf.Data.Value values = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>repeated .MBolli.PhpGeobuf.Data.Value values = 13;</code>
     * @param \MBolli\PhpGeobuf\Data\Value[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \MBolli\PhpGeobuf\Data\Value::class);
        $this->values = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 custom_properties = 15 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCustomProperties()
    {
        return $this->custom_properties;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 custom_properties = 15 [packed = true];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCustomProperties($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->custom_properties = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Geometry::class, \MBolli\PhpGeobuf\Data_Geometry::class);

